### ISSUE TITLE
when using helm as cfg mgmt, make it possible to point to chart url instead of path

### ISSUE THREAD

**Issue by krancour** [akuity/kargo-render#100]

**Comment by daftping** [comment]
@krancour could you please confirm that helm charts from remote repositories are not supported right now?
I can't use Kargo Render for configurations like this for example.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```
