### ISSUE TITLE
Support basic regex and templating in Bookfile.yaml

### ISSUE THREAD

**Issue by krancour** [akuity/kargo-render#103]
`Bookfile.yaml` can get pretty repetative -- which creates opportunities for human error.

Consider the following case lifted directly from our dogfooding efforts in the akuity-platform-deploy repo:

```
configVersion: v1alpha1
branchConfigs:
  bookkeeper/env/prod:
    appConfigs:
      akuity-platform:
        configManagement:
          kustomize:
            path: env/prod/akuity-platform/usw2
        outputPath: prod/akuity-platform/usw2
        combineManifests: true
      monitoring:
        configManagement:
          kustomize:
            path: env/prod/monitoring/usw2
        outputPath: prod/monitoring/usw2
        combineManifests: true
      overprovisioner:
        configManagement:
          kustomize:
            path: env/prod/overprovisioner/usw2
        outputPath: prod/overprovisioner/usw2
        combineManifests: true
    prs:
      enabled: true
  bookkeeper/env/stage:
    appConfigs:
      akuity-platform:
        configManagement:
          kustomize:
            path: env/stage/akuity-platform/usw2
        outputPath: stage/akuity-platform/usw2
        combineManifests: true
      monitoring:
        configManagement:
          kustomize:
            path: env/stage/monitoring/usw2
        outputPath: stage/monitoring/usw2
        combineManifests: true
      overprovisioner:
        configManagement:
          kustomize:
            path: env/stage/overprovisioner/usw2
        outputPath: stage/overprovisioner/usw2
        combineManifests: true
  bookkeeper/env/test:
    appConfigs:
      akuity-platform:
        configManagement:
          kustomize:
            path: env/test/akuity-platform/usw2
        outputPath: test/akuity-platform/usw2
        combineManifests: true
      monitoring:
        configManagement:
          kustomize:
            path: env/test/monitoring/usw2
        outputPath: test/monitoring/usw2
        combineManifests: true
      overprovisioner:
        configManagement:
          kustomize:
            path: env/test/overprovisioner/usw2
        outputPath: test/overprovisioner/usw2
        combineManifests: true

```

Because the  rules for what path Kustomize reads from and what path Bookkeeper will write manifests to are consistently, _for every environment_, a function of the environment's name, we can _almost_ express the above more succinctly as follows:

```yaml
configVersion: v1alpha1
branchConfigs:
  bookkeeper/env/([\w-]+):
    appConfigs:
      akuity-platform:
        configManagement:
          kustomize:
            path: env/${1}/akuity-platform/usw2
        outputPath: ${1}/akuity-platform/usw2
        combineManifests: true
      monitoring:
        configManagement:
          kustomize:
            path: env/${1}/monitoring/usw2
        outputPath: ${1}/monitoring/usw2
        combineManifests: true
      overprovisioner:
        configManagement:
          kustomize:
            path: env/${1}/overprovisioner/usw2
        outputPath: ${1}/overprovisioner/usw2
        combineManifests: true
```

The one thing we cannot account for entirely here is that we had a special rule for production only that we should open PRs against the production branch instead of committing directly to it. There are probably some techniques we could use to accommodate that.

One approach would be to use the above for test and stage environments and then have separate configuration for production only. If we count the name of the production branch as matching a literal string _more exactly_ than it matches the regex, then we can favor the configuration from the more exact match.

Since the question of whether to commit directly or open a PR is probably one of the few settings that is likely to vary from one environment to the next, another option might be to break the rules about this into their own top-level section. i.e. Just list branches for which PRs should be opened instead of committing directly.

We could also combine those two approaches, which is what I think I favor at the moment.
