### ISSUE TITLE
Kustomize render options not working as expected (path, buildOptions)

### ISSUE THREAD

**Issue by dwkop** [akuity/kargo-render#231]
It seems that the documentation is outdated.
In the current version `0.33`, `configManagement` requires a `kustomization` and just below the path.

Working example:
```yaml
configVersion: v1alpha1
branchConfigs:
- name: stage/dev
  appConfigs:
    demo:
      configManagement:
        kustomize:
          path: stages/dev
      outputPath: demo
```
Docu: https://kargo-render.akuity.io/how-to-guides/configuration

Furthermore the `buildOptions` are not supported, which according to here: https://github.com/akuity/kargo-render/blob/main/schema.json#L106 should be allowed.

Following yaml fails with error

```yaml
configVersion: v1alpha1
branchConfigs:
- name: stage/dev
  appConfigs:
    demo:
      configManagement:
        kustomize:
          path: kargo-demo-kustomize/stages/dev
        buildOptions: "--load-restrictor LoadRestrictionsNone"
      outputPath: demo
```
```bash
time="2024-01-03T12:22:06Z" level=error msg="error executing Promotion: error executing Git-based promotion mechanisms: error executing Kargo Render promotion mechanisms: error rendering manifests for git repo \"https://gh-enterprise.com/org/kargo-demo-service\" via Kargo Render: error rendering manifests: error executing cmd [/usr/local/bin/kargo-render render --repo https://gh-enterprise.com/org/kargo-demo-service --ref --target-branch stage/dev --repo-username cortex-bot --output json --image artifacts.rbi.tech/docker/org/cortex-template-kustomize-application/nginx:2023.52.13]: Error: error loading Kargo Render configuration from repo: error normalizing and validating Kargo Render configuration: error validating Kargo Render configuration: branchConfigs.0.appConfigs.demo.configManagement: Must validate one and only one schema (oneOf); branchConfigs.0.appConfigs.demo.configManagement.kustomize: Additional property buildOptions is not allowed\n" freight=4fadca4b6a0c9f671f143df43e50272e920108...
```
