### ISSUE TITLE
Rendering for helm fails trying to make a directory when umbrella chart is used

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo-render#249]
I have a Helm Umbrella chart like:
```
apiVersion: v2
name: prometheus
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: prometheus
    version: 25.0.0
    repository: https://prometheus-community.github.io/helm-charts
```

With the kargo-render config as:
```
configVersion: v1alpha1
branchConfigs:
- name: env/dev
    prometheus:
      configManagement:
        path: helm/prometheus-umbrella
        helm:
          releaseName: prometheus
          namespace: prometheus
          valueFiles:
          - values-dev.yaml
      outputPath: prometheus
```

Add the Github workflow action:
```
permissions: 
  contents: write
  pull-requests: write

jobs:
  render-dev-manifests:
    name: Render `dev` manifests
    runs-on: ubuntu-latest
    steps:
    - run: id
    - run: sudo mkdir -p /github/home/.config && sudo chown -R runner /github/home/ && ls -ld /github/home && ls -la /github/home
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/dev
```

That fails on 
```
helm repo add https:--prometheus-community.github.io-helm-charts https://prometheus-community.github.io/helm-charts 
failed exit status 1: Error: mkdir /github/home/.config: permission denied
```

The full logs:
```
Run akuity/kargo-render-action@v0.1.0-rc.35
/usr/bin/docker run --name ghcrioakuitykargorenderv010rc35_0d0[6](https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210#step:3:7)a3 --label [7](https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210#step:3:8)78f46 --workdir /github/workspace --rm -e "INPUT_PERSONALACCESSTOKEN" -e "INPUT_TARGETBRANCH" -e "INPUT_ALLOWEMPTY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER
time="2024-03-06T20:53:54Z" level=info msg="Starting Kargo Render Action" commit=933ffd41e2783e6cb1ee28c3fa6290a60ffd619c version=v0.1.0-rc.35
time="2024-03-06T20:53:55Z" level=info msg="kustomize build /tmp/163096[8](https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210#step:3:9)315/repo/kustomize/overlays/dev" dir= execID=1f7bf
time="2024-03-06T20:53:55Z" level=info msg=Trace args="[kustomize build /tmp/1630[9](https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210#step:3:10)68315/repo/kustomize/overlays/dev]" dir= operation_name="exec kustomize" time_ms=14.155033
time="2024-03-06T20:53:55Z" level=info msg="helm template . --name-template prometheus --namespace prometheus --values /tmp/1630968315/repo/helm/prometheus-umbrella/values-dev.yaml --include-crds" dir=/tmp/1630968315/repo/helm/prometheus-umbrella execID=5e75c
time="2024-03-06T20:53:55Z" level=error msg="`helm template . --name-template prometheus --namespace prometheus --values /tmp/1630968315/repo/helm/prometheus-umbrella/values-dev.yaml --include-crds` failed exit status 1: Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: prometheus" execID=5e75c
time="2024-03-06T20:53:55Z" level=info msg=Trace args="[helm template . --name-template prometheus --namespace prometheus --values /tmp/1630968315/repo/helm/prometheus-umbrella/values-dev.yaml --include-crds]" dir=/tmp/1630968315/repo/helm/prometheus-umbrella operation_name="exec helm" time_ms=37.083433
time="2024-03-06T20:53:55Z" level=info msg="helm repo add https:--prometheus-community.github.io-helm-charts https://prometheus-community.github.io/helm-charts" dir=/tmp/1630968315/repo/helm/prometheus-umbrella execID=3095b
time="2024-03-06T20:53:55Z" level=error msg="`helm repo add https:--prometheus-community.github.io-helm-charts [https://prometheus-community.github.io/helm-charts`](https://prometheus-community.github.io/helm-charts%60) failed exit status 1: Error: mkdir /github/home/.config: permission denied" execID=3095b
time="2024-03-06T20:53:55Z" level=info msg=Trace args="[helm repo add https:--prometheus-community.github.io-helm-charts https://prometheus-community.github.io/helm-charts]" dir=/tmp/16309683[15](https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210#step:3:16)/repo/helm/prometheus-umbrella operation_name="exec helm" time_ms=37.672883999999996
time="2024-03-06T20:53:55Z" level=fatal msg="error pre-rendering manifests: error generating manifests using Argo CD repo server: `helm repo add https:--prometheus-community.github.io-helm-charts [https://prometheus-community.github.io/helm-charts`](https://prometheus-community.github.io/helm-charts%60) failed exit status 1: Error: mkdir /github/home/.config: permission denied"
```
https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178615225/job/22362923210

The `/github/home` directory doesn't even exist.
```
Run ls -dv /github/home
ls: cannot access '/github/home': No such file or directory
Error: Process completed with exit code 2.
```
https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178768340/job/22363418503

Even if I make the directory first and give the `runner` user ownership:
```
Run sudo mkdir -p /github/home/.config && sudo chown -R runner /github/home/ && ls -ld /github/home && ls -la /github/home
drwxr-xr-x 3 runner root 4096 Mar  6
total 12
drwxr-xr-x 3 runner root  .
drwxr-xr-x 3 root   root 4096 Mar  6 21:17 ..
drwxr-xr-x 2 runner root 4096 Mar  6 21:17 .config
```

It still fails trying to `mkdir` the directory:
```
time="2024-03-06T21:17:24Z" level=fatal msg="error pre-rendering manifests: error generating manifests using Argo CD repo server: `helm repo add https:--prometheus-community.github.io-helm-charts [https://prometheus-community.github.io/helm-charts`](https://prometheus-community.github.io/helm-charts%60) failed exit status 1: Error: mkdir /github/home/.config: permission denied"
```
https://github.com/morey-tech/rendered-manifests-example/actions/runs/8178893234/job/22363785538

Full example: https://github.com/morey-tech/rendered-manifests-example/tree/b8d8b77aeb5dacef6c1c8ec3f3b5bde813b58c87

**Comment by morey-tech** [comment]
Workaround, tell Helm to use `/tmp` instead:
```
jobs:
  render-dev-manifests:
    name: Render `dev` manifests
    runs-on: ubuntu-latest
    steps:
    - run: echo $HOME
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/dev
      env:
        XDG_CONFIG_HOME: /tmp
        XDG_CACHE_HOME: /tmp
        XDG_DATA_HOME: /tmp
```
