### ISSUE TITLE
Kustomization fails if a patch file contains multiple Yaml documents

### ISSUE THREAD

**Issue by evgeny-goldin** [akuity/kargo-render#287]
kustomization.yaml:

```
patches:
- path: overlays/file.yaml
```

overlays/file.yaml:

```
apiVersion: batch/v1
kind: CronJob
..
---
apiVersion: batch/v1
kind: CronJob
..
```

causes Kargo render to fail

```
time="2024-06-10T23:22:14Z" level=error msg="`kustomize build /tmp/1907128327/repo/env/dev/aws/akuity-platform --enable-helm --load-restrictor LoadRestrictionsNone` failed exit status 1: Error: trouble configuring builtin PatchTransformer with config: `\npath: overlays/archiver-cronjobs.yaml\n`: unable to parse SM or JSON patch from [..]" execID=71462
```

**Comment by krancour** [comment]
@alexmt is this possibly a repo server bug? We no longer invoke `kargo build` directly.

**Comment by alexmt** [comment]
I think kustomize does not support having multiple patches in one file. Tried it with the following kustomization and got the same error:

<details>
  <summary>kustomization.yaml</summary>

  ```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

patches:
- path: patch.yaml 
 
```
</details>

<details>
  <summary>resources.yaml</summary>

  ```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob2
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
</details>

<details>
  <summary>patch.yaml</summary>

  ```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob1
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1
            image: busybox1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob2
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1
            image: busybox1
```
</details>


```
kustomize build . 
Error: trouble configuring builtin PatchTransformer with config: `
path: patch.yaml
`: unable to parse SM or JSON patch from
```

So closing the issue. Please reopen if I'm missing something
