### ISSUE TITLE
Error rendering kube-prometheus stack with includeCRDs

### ISSUE THREAD

**Issue by hoopty** [akuity/kargo-render#294]
When using the below with kustomize + helm, I get thee error:

```
time="2024-06-26T02:18:44Z" level=info msg="Starting Kargo Render Action" commit=2248e73dfa633d768d0ac528c8da16d153cfb6f6 version=v0.1.0-rc.40
time="2024-06-26T02:19:03Z" level=fatal msg="error writing manifests for app \"prometheus\" to \"/tmp/repo-293497742/repo/manifests/prometheus\": error unmarshaling resource: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context"
```

As a workaround, if I disable the `includeCRDs: true` then kargo-render will at least run (but then it won't include up-to-date CRD's for ArgoCD).  I have tried with no values.yaml overrides from chart defaults to verify that it is not my settings that are an issue.

Here's my `helmChart.yaml`:
```apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: prometheus
releaseName: prometheus
namespace: prometheus
repo: https://prometheus-community.github.io/helm-charts
name: kube-prometheus-stack
includeCRDs: true
valuesFile: ../../../addons/prometheus/base/values.yaml
additionalValuesFiles:
  - ./values.yaml
version: 60.4.0
```

Here's the relevant `kargo-render.yaml` snippet:
```
      prometheus:
        configManagement:
          path: clusters/${1}/prometheus
          kustomize:
            buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
        outputPath: manifests/prometheus
```
