### ISSUE TITLE
Leave room to use ArgoCD repo server for manifest rendering

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo-render#86]
The proposal is to slightly change `configManagement` setting structure to make it possible to use argocd repo server for manifest rendering.

Here is an example of config management section:

```yaml
      akuity-platform:
        configManagement:
          kustomize:
            path: env/prod/akuity-platform/usw2
```

I suggest to re-use Argo CD `source` structure for supported field:

https://github.com/argoproj/argo-cd/blob/434f35eec54adf7842ddc2d6d19b28436e2114ee/docs/operator-manual/application.yaml#L18

So updated config management would look like this:

```yaml
      akuity-platform:
        configManagement:
          path: env/prod/akuity-platform/usw2
          kustomize: {}
```

This would allow us to eventually drop internal rendering implementation and re-use Argo CD helm/kustomize/plugins integation
